Vagrant.configure("2") do |config|
  # Definir a imagem base para todas as VMs
  config.vm.box = "bento/ubuntu-20.04"

  # Configuração do Control Plane
  config.vm.define "control-plane" do |cp|
    cp.vm.hostname = "control-plane"
    cp.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
    cp.vm.network "private_network", type: "dhcp"
  end

  # Criando os 2 Workers
  (1..2).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.hostname = "worker-#{i}"
      worker.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
      worker.vm.network "private_network", type: "dhcp"
    end
  end
end

